/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf,v 5.0 2002/04/20 07:30:13 hardaker Exp $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "nstAgentModuleObject.h"

/*
 * the variable we want to tie an OID to.  The agent will handle all
 * * GET and SET requests to this variable changing it's value as needed.
 */

static long nstAgentModuleObject[30];


/*
 * our initialization routine, automatically called by the agent 
 * (to get called, the function name must match init_FILENAME()) 
 */
void
init_nstAgentModuleObject(void)
{
    static int     nstAgentModuleObject_oid[25][13] = {{ 1, 3, 6, 1, 4, 1, 8072, 2, 4, 1, 1, 1, 0 }};

    for ( int i = 1; i < 25 ; i++ )
    {
        for (int j = 0 ; j < 13 ; j++ )
        {
            if ( j < 12)
            {
                nstAgentModuleObject_oid[i][j] = nstAgentModuleObject_oid[0][j];
            }
            else
            {
                nstAgentModuleObject_oid[i][j] = i;
            }
            //printf(",%d" , nstAgentModuleObject_oids[i][j]);
        }
        //printf("\n");
    }
	for ( int i = 0 ; i < 25 ; i++ )
	{
	    //*(nstAgentModuleObject_oids[i]) = { 1, 3, 6, 1, 4, 1, 8072, 2, 4, 1, 1, 1, i };
		netsnmp_register_long_instance("nstAgentModuleObject",
		                              nstAgentModuleObject_oid[i],
		                              OID_LENGTH(nstAgentModuleObject_oid[i]),
		                              &nstAgentModuleObject[i], NULL);
	}
}
