#!/bin/sh
sleep 5
ip addr flush dev eth0
sleep 1
ip addr add 192.168.1.38/255.255.255.0 broadcast 192.168.1.255 dev eth0
sleep 1
snmpd -Lo
/root/smartReset.sh &
/root/Projects/RAIIS/ShatterMe/ShatterMe
