#!/bin/bash

ACTIVE_WIN_ID=$(xdotool getwindowfocus)
ACTIVE_WIN_PID=$(xdotool getwindowpid $ACTIVE_WIN_ID)
ACTIVE_WIN_PROCESS=$(cat "/proc/$ACTIVE_WIN_PID/comm")

if [[ "$ACTIVE_WIN_PROCESS" = "evince"
 	|| "$ACTIVE_WIN_PROCESS" = "com.github.john" ]]; then
	xdotool key Right
elif [ "$ACTIVE_WIN_PROCESS" = "spotify" ]; then
	xdotool key Ctrl+Right
elif [ "$ACTIVE_WIN_PROCESS" = "firefox" ]; then
	xdotool key Ctrl+Tab
elif [ "$ACTIVE_WIN_PROCESS" = "nautilus" ]; then
	xdotool key Return
elif [ "$ACTIVE_WIN_PROCESS" = "gedit" ]; then
	xdotool key Ctrl+Alt+Page_Down
else
	echo "'$ACTIVE_WIN_PROCESS'"
fi
