#!/bin/bash

ACTIVE_WIN_ID=$(xdotool getwindowfocus)
ACTIVE_WIN_PID=$(xdotool getwindowpid $ACTIVE_WIN_ID)
ACTIVE_WIN_PROCESS=$(cat "/proc/$ACTIVE_WIN_PID/comm")

if [ "$ACTIVE_WIN_PROCESS" = "nautilus" ]; then
	xdotool key Left
elif [ "$ACTIVE_WIN_PROCESS" = "spotify" ]; then
	xdotool key Ctrl+Down
elif [ "$ACTIVE_WIN_PROCESS" = "firefox" ]; then
	xdotool key u
elif [ "$ACTIVE_WIN_PROCESS" = "qtcreator" ]; then
	xdotool key Page_Up
else
	echo "'$ACTIVE_WIN_PROCESS'"
fi
