#!/bin/bash

function getWheelSpeed
{
	if [[ "$1" == "1" ]]; then

        echo "13"

    elif [[ "$1" == "2" ]]; then

        echo "14"

    elif [[ "$1" == "3" ]]; then

        echo "20"

    elif [[ "$1" == "4" ]]; then

        echo "24"

    elif [[ "$1" == "5" ]]; then

        echo "30"

    elif [[ "$1" == "6" ]]; then

        echo "36"

    elif [[ "$1" == "7" ]]; then

        echo "42"

    elif [[ "$1" == "8" ]]; then

        echo "50"

    elif [[ "$1" == "9" ]]; then

        echo "60"

    fi
}
