#!/bin/bash

ACTIVE_WIN_ID=$(xdotool getwindowfocus)
ACTIVE_WIN_PID=$(xdotool getwindowpid $ACTIVE_WIN_ID)
ACTIVE_WIN_PROCESS=$(cat "/proc/$ACTIVE_WIN_PID/comm")

SCREEN_S=$(xrandr | grep "*" | awk '{print $1}') #Screen size
SCREEN_W=$(echo "$SCREEN_S" | awk -F 'x' '{print $1}')
SCREEN_H=$(echo "$SCREEN_S" | awk -F 'x' '{print $2}')

if [ "$ACTIVE_WIN_PROCESS" = "evince" ]; then
	SCREEN_HALF_W=$((SCREEN_W / 4))
	SCREEN_HALF_H=$((SCREEN_H / 2))
	
	xdotool mousemove "$SCREEN_HALF_W" "$SCREEN_HALF_H"
	xdotool click 3
	xdotool key Up
	xdotool key Up
	xdotool key Up
	xdotool key Return
elif [ "$ACTIVE_WIN_PROCESS" = "spotify" ]; then
	xdotool key KP_Space
elif [ "$ACTIVE_WIN_PROCESS" = "firefox" ]; then
	SCREEN_HALF_W=$((SCREEN_W - 100))
	SCREEN_HALF_H=$((SCREEN_H / 2))
	xdotool mousemove "$SCREEN_HALF_W" "$SCREEN_HALF_H"
	xdotool click 2
	echo "$SCREEN_HALF_W" > /tmp/rbd
	echo "$SCREEN_HALF_H" >> /tmp/rbd
	
	
	sleep 0.1
	xdotool mousemove_relative 0 13
else
	echo "$ACTIVE_WIN_PROCESS"
fi

