#! /bin/bash

if [ "$#" = "1" ]; then
	echo "Start native mode"
	cd /home/bijan/Project/RAIIS/Rebound

	QUERY_CMD='{getline;{if(/kbd/==1){ print $3;exit 0;}}}}'
	DEV_FILE="/proc/bus/input/devices"
	EVENT_FILE=$(cat $DEV_FILE | awk '/Xbox/{for(a=0;a>=0;a++)'"$QUERY_CMD")
	#	EVENT_FILE="event27"
	EV_NUM=$(echo "$EVENT_FILE" | awk -F 't' '{print $2}')
	echo "$EV_NUM"

	if [ "$EVENT_FILE" ]; then
		./Rebound "$EV_NUM"
	else
		echo "Error: No device found"
	fi
else
	echo "Start server mode"
	cd /home/bijan/Project/RAIIS/Rebound
	./Rebound
fi
