#! /bin/bash

if [ "$#" = "1" ]; then
	echo "Start native mode"
	cd /home/bijan/Project/RAIIS/Rebound

	QUERY_CMD='{getline;{if(/kbd/==1){ print $3;exit 0;}}}}'
	DEV_FILE="/proc/bus/input/devices"
	EVENT_FILE=$(cat $DEV_FILE | awk '/Xbox/{for(a=0;a>=0;a++)'"$QUERY_CMD")

	if [ "$EVENT_FILE" ]; then
		evtest "/dev/input/$EVENT_FILE" | ./Rebound -native
	else
		echo "Error: No device found"
	fi
else
	echo "Start server mode"
	cd /home/bijan/Project/RAIIS/Rebound
	./Rebound
fi
